title: Programming stories
author: Pavel Likin
email: pavellikin@gmail.com
description: Programming stories
twitter_username: burnout171
github_username:  burnout171
encoding: utf-8
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: UA-112055662-1

paginate: 5