title: Истории одного программиста
author: Pavel Likin
email: pavellikin@gmail.com
encoding: utf-8
markdown: kramdown
theme: minima

twitter_username: burnout171
github_username: burnout171
linkedin_username: pavellikin
rss: /feed.xml

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

google_analytics: UA-112055662-1

paginate: 5