title: Pavel Likin`s blog
author: Pavel Likin
email: pavellikin@gmail.com
description: Stories about programming.
twitter_username: burnout171
github_username:  burnout171
encoding: utf-8
pagination: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

google_analytics: UA-112055662-1
