title: Programming stories
author: Pavel Likin
email: pavellikin@gmail.com
description: Programming stories
twitter_username: burnout171
github_username:  burnout171
encoding: utf-8
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-112055662-1

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'